/*
 http://creativecommons.org/licenses/by/2.5/
 - Free for use in both personal and commercial projects
 - Attribution requires leaving author name, author link, and the license info intact
*/
(function(){var c=jQuery,y=function(){function c(){this.na=500;this.Ga=!0;this.la=700;this.sa=50;this.Oa=!0;this.ra=this.Ea=!1}c.prototype.Da=function(a,b){return"Image "+a+" of "+b};return c}(),C=function(){function d(a){this.options=a;this.fa=[];this.ha=void 0;this.init()}d.prototype.init=function(){this.enable();this.Fa()};d.prototype.enable=function(){var a=this;c("body").on("click","a[rel^=lightbox], area[rel^=lightbox], a[data-lightbox], area[data-lightbox]",function(b){a.start(c(b.currentTarget));
return!1})};d.prototype.Fa=function(){var a=this;c("<div id='lightboxOverlay' class='lightboxOverlay'></div><div id='lightbox' class='lightbox'><div class='lb-outerContainer'><div class='lb-container'><canvas id='pano-canvas' class='lb-canvas' /><img class='lb-image' src='' /><div class='lb-nav'><a class='lb-prev' href='' ></a><a class='lb-next' href='' ></a></div><div class='lb-pano_nav'><a class='lb-pano_prev' href='' ></a><a class='lb-pano_next' href='' ></a></div><div class='lb-pano_control'><a class='lb-pano_full' href='' ></a><a class='lb-pano_full_back' href='' ></a><input type=range class='lb-pano_zoom' min=0 value=40 max=100 /></div><div class='lb-loader'><a class='lb-cancel'></a></div></div></div><div class='lb-dataContainer'><div class='lb-data'><div class='lb-details'><span class='lb-caption'></span><span class='lb-number'></span></div><div class='lb-closeContainer'><a class='lb-close'></a></div></div></div></div>").appendTo(c("body"));
this.ea=c("#lightbox");this.ma=c("#lightboxOverlay");this.ga=this.ea.find(".lb-outerContainer");this.ka=this.ea.find(".lb-container");this.xa=parseInt(this.ka.css("padding-top"),10);this.wa=parseInt(this.ka.css("padding-right"),10);this.ua=parseInt(this.ka.css("padding-bottom"),10);this.va=parseInt(this.ka.css("padding-left"),10);this.ma.hide().on("click",function(){a.end();return!1});this.ea.hide().on("click",function(b){"lightbox"===c(b.target).attr("id")&&a.end();return!1});this.ga.on("click",
function(b){"lightbox"===c(b.target).attr("id")&&a.end();return!1});this.ea.find(".lb-prev").on("click",function(){0===a.ha?a.ja(a.fa.length-1):a.ja(a.ha-1);return!1});this.ea.find(".lb-next").on("click",function(){a.ha===a.fa.length-1?a.ja(0):a.ja(a.ha+1);return!1});this.ea.find(".lb-pano_prev").on("click",function(){0===a.ha?a.ja(a.fa.length-1):a.ja(a.ha-1);return!1});this.ea.find(".lb-pano_next").on("click",function(){a.ha===a.fa.length-1?a.ja(0):a.ja(a.ha+1);return!1});this.ea.find(".lb-loader, .lb-close").on("click",
function(){a.end();return!1});this.ea.find(".lb-pano_full").on("click",function(){a.Ka();return!1});this.ea.find(".lb-pano_full_back").on("click",function(){a.La();return!1});this.ea.find(".lb-pano_zoom").on("input",function(){a.Ma(a.ea.find(".lb-pano_zoom").val());return!1});this.pa=this.ea.find(".lb-canvas").width();this.oa=this.ea.find(".lb-canvas").height();this.ea.find(".lb-canvas").width("auto");this.ea.find(".lb-canvas").height("auto")};d.prototype.start=function(a){function b(a){d.fa.push({link:a.attr("href"),
title:a.attr("data-title")||a.attr("title"),Aa:a.attr("pano-type"),pa:a.attr("pano-width"),oa:a.attr("pano-height")})}var d=this,e=c(window);e.on("resize",c.proxy(this.qa,this));c("select, object, embed").css({visibility:"hidden"});this.qa();this.fa=[];var g=0,f=a.attr("data-lightbox");if(f)for(var f=c(a.prop("tagName")+'[data-lightbox="'+f+'"]'),k=0;k<f.length;k=++k)b(c(f[k])),f[k]===a[0]&&(g=k);else if("lightbox"===a.attr("rel"))b(a);else for(f=c(a.prop("tagName")+'[rel="'+a.attr("rel")+'"]'),k=
0;k<f.length;k=++k)b(c(f[k])),f[k]===a[0]&&(g=k);a=e.scrollTop()+this.options.sa;e=e.scrollLeft();this.ea.css({top:a+"px",left:e+"px"}).fadeIn(this.options.na);this.ja(g)};d.prototype.ja=function(a){var b=this;this.ya();var d=this.ea.find(".lb-image");this.ma.fadeIn(this.options.na);c(".lb-loader").fadeIn("slow");this.ea.find(".lb-image, .lb-nav, .lb-prev, .lb-next, .lb-dataContainer, .lb-numbers, .lb-caption").hide();this.ea.find(".lb-canvas, .lb-pano_nav, .lb-pano_prev, .lb-pano_next, .lb-pano_control, .lb-pano_full, .lb-pano_full_back").hide();
this.ga.addClass("animating");var e=new Image;e.onload=function(){var g,f;d.attr("src",b.fa[a].link);c(e);null!=b.fa[a].Aa&&(null==b.ia&&(b.ia=new Pano,b.ia.init(b.ea.find(".lb-canvas").get(0))),b.ia.isAvailable()&&(e.width=null!=b.fa[a].pa?b.fa[a].pa:b.pa,e.height=null!=b.fa[a].oa?b.fa[a].oa:b.oa));d.width(e.width);d.height(e.height);b.options.Ga&&(g=c(window).width(),f=c(window).height(),g=g-b.va-b.wa-20,f=f-b.xa-b.ua-120,e.width>g||e.height>f)&&(e.width/g>e.height/f?(f=g,g=parseInt(e.height/(e.width/
f),10)):(g=f,f=parseInt(e.width/(e.height/g),10)),d.width(f),d.height(g));b.Qa(d.width(),d.height())};e.src=this.fa[a].link;this.ha=a};d.prototype.qa=function(){this.ma.width(c(window).width()).height(c(document).height())};d.prototype.Qa=function(a,b){function d(){e.ea.find(".lb-dataContainer").width(k);e.ea.find(".lb-prevLink").height(n);e.ea.find(".lb-nextLink").height(n);null!=e.fa[e.ha].Aa&&e.ia.isAvailable()?e.Pa(a,b):e.Na()}var e=this,g=this.ga.outerWidth(),f=this.ga.outerHeight(),k=a+this.va+
this.wa,n=b+this.xa+this.ua;if(this.ta){this.ea.addClass("animating");var y=c(window).scrollTop()+this.options.sa;this.ea.animate({top:y+"px"},this.options.la,"swing",function(){e.ea.removeClass("animating");e.ta=!1})}g!==k||f!==n?this.ga.animate({width:k,height:n},this.options.la,"swing",function(){d()}):d()};d.prototype.Na=function(){this.ea.find(".lb-loader").hide();this.ea.find(".lb-image").fadeIn("slow");this.Ra();this.Ca();this.Ba();this.za()};d.prototype.Pa=function(a,b){this.ea.find(".lb-loader").hide();
this.ea.find(".lb-canvas").fadeIn("slow");this.Sa();this.Ca();this.Ba();this.za();this.ea.find(".lb-canvas").get(0).width=a;this.ea.find(".lb-canvas").get(0).height=b;this.ia.setSize(a,b);var c=this.ea.find(".lb-image");this.ia.setImage(c.get(0));this.ea.find(".lb-pano_zoom").val(this.ia.getFovScale())};d.prototype.Ra=function(){var a=!1;try{document.createEvent("TouchEvent"),a=this.options.Ea?!0:!1}catch(b){}this.ea.find(".lb-nav").show();1<this.fa.length&&(this.options.ra?(a&&this.ea.find(".lb-prev, .lb-next").css("opacity",
"1"),this.ea.find(".lb-prev, .lb-next").show()):(0<this.ha&&(this.ea.find(".lb-prev").show(),a&&this.ea.find(".lb-prev").css("opacity","1")),this.ha<this.fa.length-1&&(this.ea.find(".lb-next").show(),a&&this.ea.find(".lb-next").css("opacity","1"))))};d.prototype.Sa=function(){this.ea.find(".lb-pano_nav").show();this.ea.find(".lb-pano_control").show();this.ea.find(".lb-pano_full").show();this.ea.find(".lb-pano_full").css("opacity","1");this.ea.find(".lb-pano_zoom").show();1<this.fa.length&&(this.options.ra?
(this.ea.find(".lb-pano_prev, .lb-pano_next").css("opacity","1"),this.ea.find(".lb-pano_prev, .lb-pano_next").show()):(0<this.ha&&(this.ea.find(".lb-pano_prev").show(),this.ea.find(".lb-pano_prev").css("opacity","1")),this.ha<this.fa.length-1&&(this.ea.find(".lb-pano_next").show(),this.ea.find(".lb-pano_next").css("opacity","1"))))};d.prototype.Ca=function(){var a=this;if("undefined"!==typeof this.fa[this.ha].title&&""!==this.fa[this.ha].title)this.ea.find(".lb-caption").html(this.fa[this.ha].title).fadeIn("fast").find("a").on("click",
function(){location.href=c(this).attr("href")});1<this.fa.length&&this.options.Oa?this.ea.find(".lb-number").text(this.options.Da(this.ha+1,this.fa.length)).fadeIn("fast"):this.ea.find(".lb-number").hide();this.ga.removeClass("animating");this.ea.find(".lb-dataContainer").fadeIn(this.options.la,function(){return a.qa()})};d.prototype.Ba=function(){this.fa.length>this.ha+1&&((new Image).src=this.fa[this.ha+1].link);0<this.ha&&((new Image).src=this.fa[this.ha-1].link)};d.prototype.za=function(){c(document).on("keyup.keyboard",
c.proxy(this.Ha,this))};d.prototype.ya=function(){c(document).off(".keyboard")};d.prototype.Ha=function(a){a=a.keyCode;var b=String.fromCharCode(a).toLowerCase();if(27===a||b.match(/x|o|c/))this.end();else if("p"===b||37===a)0!==this.ha?this.ja(this.ha-1):this.options.ra&&1<this.fa.length&&this.ja(this.fa.length-1);else if("n"===b||39===a)this.ha!==this.fa.length-1?this.ja(this.ha+1):this.options.ra&&1<this.fa.length&&this.ja(0)};d.prototype.end=function(){this.ya();c(window).off("resize",this.qa);
this.ea.fadeOut(this.options.na);this.ma.fadeOut(this.options.na);c("select, object, embed").css({visibility:"visible"})};d.prototype.Ka=function(){var a=this;if(null!=this.ia&&!this.ia.fullscreen()){this.ea.find(".lb-pano_full").hide();this.ea.find(".lb-pano_zoom").hide();c("body").css({overflow:"hidden"});this.ea.addClass("animating");var b=c(window).scrollTop();this.ta=!0;this.ea.animate({top:b+"px"},this.options.la,"swing",function(){a.ea.removeClass("animating")});var d=a.ga.width()-a.ka.width(),
e=a.ga.height()-a.ka.height(),g=setInterval(function(){var b=a.ga.width()-d,c=a.ga.height()-e;a.ia.setSize(b,c)},1E3/60);this.Ja=a.ga.width();this.Ia=a.ga.height();this.ga.addClass("animating");this.ga.animate({width:window.innerWidth,height:window.innerHeight},this.options.la,"swing",function(){a.ga.removeClass("animating");clearInterval(g);a.ia.setSize(a.ga.width()-d,a.ga.height()-e);a.ea.find(".lb-pano_full_back").show();a.ea.find(".lb-pano_full_back").css("opacity","1");a.ea.find(".lb-pano_zoom").show()})}};
d.prototype.La=function(){var a=this;if(null!=this.ia&&!this.ia.fullscreen()){this.ea.find(".lb-pano_full_back").hide();this.ea.find(".lb-pano_zoom").hide();this.ea.addClass("animating");var b=c(window).scrollTop()+this.options.sa;this.ea.animate({top:b+"px"},this.options.la,"swing",function(){a.ea.removeClass("animating");a.ta=!1});var d=a.ga.width()-a.ka.width(),e=a.ga.height()-a.ka.height(),g=setInterval(function(){var b=a.ga.width()-d,c=a.ga.height()-e;a.ia.setSize(b,c)},1E3/60);this.ga.addClass("animating");
this.ga.animate({width:this.Ja,height:this.Ia},this.options.la,"swing",function(){a.ga.removeClass("animating");clearInterval(g);a.ia.setSize(a.ga.width()-d,a.ga.height()-e);a.ea.find(".lb-pano_full").show();a.ea.find(".lb-pano_full").css("opacity","1");a.ea.find(".lb-pano_zoom").show();c("body").css({overflow:"auto"})})}};d.prototype.Ma=function(a){null!=this.ia&&this.ia.setFovScale(a)};return d}();c(function(){var c=new y;new C(c)})}).call(this);
