/*
 http://creativecommons.org/licenses/by/2.5/
 - Free for use in both personal and commercial projects
 - Attribution requires leaving author name, author link, and the license info intact
*/
(function(){var d=jQuery,D=function(){function d(){this.Ba=500;this.Ma=!0;this.ya=700;this.Ia=50;this.bb=!0;this.Da=this.Ra=!1}d.prototype.Qa=function(a,e){return"Image "+a+" of "+e};return d}(),E=function(){function b(a){this.options=a;this.qa=[];this.sa=void 0;this.init()}b.prototype.init=function(){this.enable();this.Sa()};b.prototype.enable=function(){var a=this;d("body").on("click","a[rel^=lightbox], area[rel^=lightbox], a[data-lightbox], area[data-lightbox]",function(e){a.start(d(e.currentTarget));
return!1})};b.prototype.Sa=function(){var a=this;d("<div id='lightboxOverlay' class='lightboxOverlay'></div><div id='lightbox' class='lightbox'><div class='lb-outerContainer'><div class='lb-container'><canvas id='pano-canvas' class='lb-canvas' /><img class='lb-image' src='' /><div class='lb-nav'><a class='lb-prev' href='' ></a><a class='lb-next' href='' ></a></div><div class='lb-pano_nav'><a class='lb-pano_prev' href='' ></a><a class='lb-pano_play' href='' ></a><a class='lb-pano_pause' href='' ></a><a class='lb-pano_next' href='' ></a></div><div class='lb-pano_control'><a class='lb-pano_full' href='' ></a><a class='lb-pano_full_back' href='' ></a><input type=range class='lb-pano_zoom' min=0 value=40 max=100 /></div><div class='lb-loader'><a class='lb-cancel'></a></div></div></div><div class='lb-dataContainer'><div class='lb-data'><div class='lb-details'><span class='lb-caption'></span><span class='lb-number'></span></div><div class='lb-closeContainer'><a class='lb-close'></a></div></div></div></div>").appendTo(d("body"));
this.pa=d("#lightbox");this.Aa=d("#lightboxOverlay");this.ta=this.pa.find(".lb-outerContainer");this.va=this.pa.find(".lb-container");this.Ha=parseInt(this.va.css("padding-top"),10);this.Ga=parseInt(this.va.css("padding-right"),10);this.Ea=parseInt(this.va.css("padding-bottom"),10);this.Fa=parseInt(this.va.css("padding-left"),10);this.Aa.hide().on("click",function(){a.end();return!1});this.pa.hide().on("click",function(e){"lightbox"===d(e.target).attr("id")&&a.end();return!1});this.ta.on("click",
function(e){"lightbox"===d(e.target).attr("id")&&a.end();return!1});this.pa.find(".lb-prev").on("click",function(){0===a.sa?a.ua(a.qa.length-1):a.ua(a.sa-1);return!1});this.pa.find(".lb-next").on("click",function(){a.sa===a.qa.length-1?a.ua(0):a.ua(a.sa+1);return!1});this.pa.find(".lb-pano_prev").on("click",function(){0===a.sa?a.ua(a.qa.length-1):a.ua(a.sa-1);return!1});this.pa.find(".lb-pano_next").on("click",function(){a.sa===a.qa.length-1?a.ua(0):a.ua(a.sa+1);return!1});this.pa.find(".lb-loader, .lb-close").on("click",
function(){a.end();return!1});this.pa.find(".lb-pano_full").on("click",function(){a.Wa();return!1});this.pa.find(".lb-pano_full_back").on("click",function(){a.Xa();return!1});this.pa.find(".lb-pano_zoom").on("input",function(){a.$a(a.pa.find(".lb-pano_zoom").val());return!1});this.pa.find(".lb-pano_play").on("click",function(){a.Za();return!1});this.pa.find(".lb-pano_pause").on("click",function(){a.Ya();return!1});this.xa=this.pa.find(".lb-canvas").width();this.wa=this.pa.find(".lb-canvas").height();
this.pa.find(".lb-canvas").width("auto");this.pa.find(".lb-canvas").height("auto")};b.prototype.start=function(a){function e(a){n.qa.push({link:a.attr("href"),title:a.attr("data-title")||a.attr("title"),za:a.attr("pano-type"),xa:a.attr("pano-width"),wa:a.attr("pano-height")})}var n=this,c=d(window);c.on("resize",d.proxy(this.Ca,this));d("select, object, embed").css({visibility:"hidden"});this.Ca();this.qa=[];var b=0,f=a.attr("data-lightbox");if(f)for(var f=d(a.prop("tagName")+'[data-lightbox="'+f+
'"]'),h=0;h<f.length;h=++h)e(d(f[h])),f[h]===a[0]&&(b=h);else if("lightbox"===a.attr("rel"))e(a);else for(f=d(a.prop("tagName")+'[rel="'+a.attr("rel")+'"]'),h=0;h<f.length;h=++h)e(d(f[h])),f[h]===a[0]&&(b=h);a=c.scrollTop()+this.options.Ia;c=c.scrollLeft();this.pa.css({top:a+"px",left:c+"px"}).fadeIn(this.options.Ba);this.ua(b)};b.prototype.ua=function(a){var e=this;this.Ka();var b=this.pa.find(".lb-image");this.Aa.fadeIn(this.options.Ba);d(".lb-loader").fadeIn("slow");this.pa.find(".lb-image, .lb-nav, .lb-prev, .lb-next, .lb-dataContainer, .lb-numbers, .lb-caption").hide();
this.pa.find(".lb-canvas, .lb-pano_nav, .lb-pano_prev, .lb-pano_next, .lb-pano_control, .lb-pano_full, .lb-pano_full_back, .lb-pano_play, .lb-pano_pause").hide();this.ta.addClass("animating");null!=this.ra&&this.ra.hasVideo()&&this.ra.clearVideo();this.sa=a;if("sphere-video"==this.qa[a].za){var c=new Image;null==this.ra&&(this.ra=new Pano,this.ra.init(this.pa.find(".lb-canvas").get(0)));this.ra.isAvailable()&&(c.width=null!=this.qa[a].xa?this.qa[a].xa:this.xa,c.height=null!=this.qa[a].wa?this.qa[a].wa:
this.wa,b.width(c.width),b.height(c.height),this.options.Ma&&(windowWidth=d(window).width(),windowHeight=d(window).height(),maxImageWidth=windowWidth-this.Fa-this.Ga-20,maxImageHeight=windowHeight-this.Ha-this.Ea-120,c.width>maxImageWidth||c.height>maxImageHeight)&&(c.width/maxImageWidth>c.height/maxImageHeight?(imageWidth=maxImageWidth,imageHeight=parseInt(c.height/(c.width/imageWidth),10)):(imageHeight=maxImageHeight,imageWidth=parseInt(c.width/(c.height/imageHeight),10)),b.width(imageWidth),b.height(imageHeight)),
this.Oa(b.width(),b.height()))}else c=new Image,c.onload=function(){var l,f;b.attr("src",e.qa[a].link);d(c);null!=e.qa[a].za&&(null==e.ra&&(e.ra=new Pano,e.ra.init(e.pa.find(".lb-canvas").get(0))),e.ra.isAvailable()&&(c.width=null!=e.qa[a].xa?e.qa[a].xa:e.xa,c.height=null!=e.qa[a].wa?e.qa[a].wa:e.wa));b.width(c.width);b.height(c.height);e.options.Ma&&(l=d(window).width(),f=d(window).height(),l=l-e.Fa-e.Ga-20,f=f-e.Ha-e.Ea-120,c.width>l||c.height>f)&&(c.width/l>c.height/f?(f=l,l=parseInt(c.height/
(c.width/f),10)):(l=f,f=parseInt(c.width/(c.height/l),10)),b.width(f),b.height(l));e.Oa(b.width(),b.height())};c.src=this.qa[a].link};b.prototype.Ca=function(){this.Aa.width(d(window).width()).height(d(document).height())};b.prototype.Oa=function(a,e){function b(){c.pa.find(".lb-dataContainer").width(h);c.pa.find(".lb-prevLink").height(A);c.pa.find(".lb-nextLink").height(A);null!=c.qa[c.sa].za&&c.ra.isAvailable()?c.cb(a,e):c.ab()}var c=this,l=this.ta.outerWidth(),f=this.ta.outerHeight(),h=a+this.Fa+
this.Ga,A=e+this.Ha+this.Ea;if(this.Ja){this.pa.addClass("animating");var D=d(window).scrollTop()+this.options.Ia;this.pa.animate({top:D+"px"},this.options.ya,"swing",function(){c.pa.removeClass("animating");c.Ja=!1})}l!==h||f!==A?this.ta.animate({width:h,height:A},this.options.ya,"swing",function(){b()}):b()};b.prototype.ab=function(){this.pa.find(".lb-loader").hide();this.pa.find(".lb-image").fadeIn("slow");this.eb();this.Pa();this.Na();this.La()};b.prototype.cb=function(a,b){this.pa.find(".lb-loader").hide();
this.pa.find(".lb-canvas").fadeIn("slow");this.fb();this.Pa();this.Na();this.La();this.pa.find(".lb-canvas").get(0).width=a;this.pa.find(".lb-canvas").get(0).height=b;this.ra.setSize(a,b);var d=this.pa.find(".lb-image");"sphere-video"==this.qa[this.sa].za?this.ra.setVideo(this.qa[this.sa].link):this.ra.setImage(d.get(0));this.pa.find(".lb-pano_zoom").val(this.ra.getFovScale())};b.prototype.eb=function(){var a=!1;try{document.createEvent("TouchEvent"),a=this.options.Ra?!0:!1}catch(b){}this.pa.find(".lb-nav").show();
1<this.qa.length&&(this.options.Da?(a&&this.pa.find(".lb-prev, .lb-next").css("opacity","1"),this.pa.find(".lb-prev, .lb-next").show()):(0<this.sa&&(this.pa.find(".lb-prev").show(),a&&this.pa.find(".lb-prev").css("opacity","1")),this.sa<this.qa.length-1&&(this.pa.find(".lb-next").show(),a&&this.pa.find(".lb-next").css("opacity","1"))))};b.prototype.fb=function(){this.pa.find(".lb-pano_nav").show();this.pa.find(".lb-pano_control").show();this.pa.find(".lb-pano_full").show();this.pa.find(".lb-pano_full").css("opacity",
"1");this.pa.find(".lb-pano_zoom").show();"sphere-video"==this.qa[this.sa].za&&(this.pa.find(".lb-pano_play").show(),this.pa.find(".lb-pano_play").css("opacity","1"),this.pa.find(".lb-pano_pause").hide(),this.pa.find(".lb-pano_pause").css("opacity","1"));1<this.qa.length&&(this.options.Da?(this.pa.find(".lb-pano_prev, .lb-pano_next").css("opacity","1"),this.pa.find(".lb-pano_prev, .lb-pano_next").show()):(0<this.sa&&(this.pa.find(".lb-pano_prev").show(),this.pa.find(".lb-pano_prev").css("opacity",
"1")),this.sa<this.qa.length-1&&(this.pa.find(".lb-pano_next").show(),this.pa.find(".lb-pano_next").css("opacity","1"))))};b.prototype.Pa=function(){var a=this;if("undefined"!==typeof this.qa[this.sa].title&&""!==this.qa[this.sa].title)this.pa.find(".lb-caption").html(this.qa[this.sa].title).fadeIn("fast").find("a").on("click",function(){location.href=d(this).attr("href")});1<this.qa.length&&this.options.bb?this.pa.find(".lb-number").text(this.options.Qa(this.sa+1,this.qa.length)).fadeIn("fast"):
this.pa.find(".lb-number").hide();this.ta.removeClass("animating");this.pa.find(".lb-dataContainer").fadeIn(this.options.ya,function(){return a.Ca()})};b.prototype.Na=function(){this.qa.length>this.sa+1&&((new Image).src=this.qa[this.sa+1].link);0<this.sa&&((new Image).src=this.qa[this.sa-1].link)};b.prototype.La=function(){d(document).on("keyup.keyboard",d.proxy(this.Ta,this))};b.prototype.Ka=function(){d(document).off(".keyboard")};b.prototype.Ta=function(a){a=a.keyCode;var b=String.fromCharCode(a).toLowerCase();
if(27===a||b.match(/x|o|c/))this.end();else if("p"===b||37===a)0!==this.sa?this.ua(this.sa-1):this.options.Da&&1<this.qa.length&&this.ua(this.qa.length-1);else if("n"===b||39===a)this.sa!==this.qa.length-1?this.ua(this.sa+1):this.options.Da&&1<this.qa.length&&this.ua(0)};b.prototype.end=function(){this.Ka();d(window).off("resize",this.Ca);this.pa.fadeOut(this.options.Ba);this.Aa.fadeOut(this.options.Ba);d("select, object, embed").css({visibility:"visible"});null!=this.ra&&this.ra.hasVideo()&&this.ra.clearVideo()};
b.prototype.Wa=function(){var a=this;if(null!=this.ra&&!this.ra.fullscreen()){this.pa.find(".lb-pano_full").hide();this.pa.find(".lb-pano_zoom").hide();d("body").css({overflow:"hidden"});this.pa.addClass("animating");var b=d(window).scrollTop();this.Ja=!0;this.pa.animate({top:b+"px"},this.options.ya,"swing",function(){a.pa.removeClass("animating")});var n=a.ta.width()-a.va.width(),c=a.ta.height()-a.va.height(),l=setInterval(function(){var b=a.ta.width()-n,d=a.ta.height()-c;a.ra.setSize(b,d)},1E3/
60);this.Va=a.ta.width();this.Ua=a.ta.height();this.ta.addClass("animating");this.ta.animate({width:window.innerWidth,height:window.innerHeight},this.options.ya,"swing",function(){a.ta.removeClass("animating");clearInterval(l);a.ra.setSize(a.ta.width()-n,a.ta.height()-c);a.pa.find(".lb-pano_full_back").show();a.pa.find(".lb-pano_full_back").css("opacity","1");a.pa.find(".lb-pano_zoom").show()})}};b.prototype.Xa=function(){var a=this;if(null!=this.ra&&!this.ra.fullscreen()){this.pa.find(".lb-pano_full_back").hide();
this.pa.find(".lb-pano_zoom").hide();this.pa.addClass("animating");var b=d(window).scrollTop()+this.options.Ia;this.pa.animate({top:b+"px"},this.options.ya,"swing",function(){a.pa.removeClass("animating");a.Ja=!1});var n=a.ta.width()-a.va.width(),c=a.ta.height()-a.va.height(),l=setInterval(function(){var b=a.ta.width()-n,d=a.ta.height()-c;a.ra.setSize(b,d)},1E3/60);this.ta.addClass("animating");this.ta.animate({width:this.Va,height:this.Ua},this.options.ya,"swing",function(){a.ta.removeClass("animating");
clearInterval(l);a.ra.setSize(a.ta.width()-n,a.ta.height()-c);a.pa.find(".lb-pano_full").show();a.pa.find(".lb-pano_full").css("opacity","1");a.pa.find(".lb-pano_zoom").show();d("body").css({overflow:"auto"})})}};b.prototype.$a=function(a){null!=this.ra&&this.ra.setFovScale(a)};b.prototype.Za=function(){null!=this.ra&&(this.pa.find(".lb-pano_play").hide(),this.pa.find(".lb-pano_pause").show(),this.ra.playVideo())};b.prototype.Ya=function(){null!=this.ra&&(this.pa.find(".lb-pano_pause").hide(),this.pa.find(".lb-pano_play").show(),
this.ra.pauseVideo())};return b}();d(function(){var b=new D;new E(b)})}).call(this);
