var g;function k(){this.M=40;this.b=this.v=30+90*(1-this.M/100);this.T=mat4.create();this.U=mat4.create();this.l=null}g=k.prototype;
g.Y=function(a){var b=this;this.canvas=a;try{this.a=a.getContext("experimental-webgl"),this.V(a.width,a.height)}catch(c){this.R=!1;return}this.R=!0;this.a.clearColor(1,0,1,1);this.a.enable(this.a.DEPTH_TEST);this.b=this.a.C/this.a.D*this.v*1;this.i=new m(this.a);this.f=new p(a,this);this.f.b=this.b;this.na=new q(this.a);var d=new r(this.a);t(d,function(){var a;a=d.a.createShader(d.a.VERTEX_SHADER);d.a.shaderSource(a,d.F[0]);d.a.compileShader(a);if(d.a.getShaderParameter(a,d.a.COMPILE_STATUS)){var c=
d.a.createShader(d.a.FRAGMENT_SHADER);d.a.shaderSource(c,d.F[1]);d.a.compileShader(c);d.a.getShaderParameter(c,d.a.COMPILE_STATUS)?(shaderPgm=d.a.createProgram(),d.a.attachShader(shaderPgm,a),d.a.attachShader(shaderPgm,c),d.a.linkProgram(shaderPgm),d.a.getProgramParameter(shaderPgm,d.a.LINK_STATUS)||alert("Unable to initialize the shader program."),shaderPgm.X=d.a.getAttribLocation(shaderPgm,"aVertexPosition"),d.a.enableVertexAttribArray(shaderPgm.X),shaderPgm.W=d.a.getAttribLocation(shaderPgm,"aTextureCoord"),
d.a.enableVertexAttribArray(shaderPgm.W),shaderPgm.ia=d.a.getUniformLocation(shaderPgm,"uPMatrix"),shaderPgm.ha=d.a.getUniformLocation(shaderPgm,"uMVMatrix"),a=shaderPgm):(alert(d.a.getShaderInfoLog(c)),a=null)}else alert(d.a.getShaderInfoLog(a)),a=null;b.A=a;u(b)})};g.fa=function(){return this.R};g.V=function(a,b){this.width=a;this.height=b;this.canvas.width=a;this.canvas.height=b;this.a.D=a;this.a.C=b;this.b=this.a.C/this.a.D*this.v*1;null!=this.f&&(this.f.b=this.b);u(this)};
g.la=function(a){var b=this;this.l=null;this.video=!1;this.O(this.M);this.f.b=this.b;b.f.reset();var c=v(a,a.src);0===c.naturalWidth?c.onload=function(){w(b.i,c,function(a){b.l=a;u(b)})}:w(this.i,c,function(a){b.l=a;u(b)})};g.ma=function(a,b){b="undefined"!==typeof b?b:15;var c=this;this.l=null;this.video=!0;this.O(this.M);this.f.b=this.b;c.f.reset();x(this.i,a,b,function(a){c.l=a;u(c)})};g.da=function(){return null!=this.i.m};
g.Z=function(){var a=this.i;null!=a.m&&(clearInterval(a.m),a.m=null,a.h.get(0).pause(),a.h.attr("src",null),a.I=!1)};g.ka=function(){this.i.play()};g.ja=function(){this.i.pause()};g.ga=function(){var a=this.i;return null!=a.m&&a.I};g.O=function(a){this.v=30+90*(1-a/100);this.b=this.a.C/this.a.D*this.v*1;this.f.b=this.b;u(this)};g.ca=function(){return-100*((this.v-30)/90-1)};
function u(a){if(null!=a.A&&(a.a.viewport(0,0,a.a.D,a.a.C),a.a.clear(a.a.COLOR_BUFFER_BIT|a.a.DEPTH_BUFFER_BIT),null!=a.l)){mat4.perspective(a.b,a.a.D/a.a.C,.1,10,a.U);var b=a.f;mat4.multiply(b.P,b.w,a.T);a.a.useProgram(a.A);a.a.activeTexture(a.a.TEXTURE0);a.a.bindTexture(a.a.TEXTURE_2D,a.l);a.a.uniform1i(a.a.getUniformLocation(a.A,"uSampler"),0);a.a.uniformMatrix4fv(a.A.ia,!1,a.U);a.a.uniformMatrix4fv(a.A.ha,!1,a.T);b=a.na;a=a.A;b.a.bindBuffer(b.a.ARRAY_BUFFER,b.B);b.a.vertexAttribPointer(a.X,b.B.S,
b.a.FLOAT,!1,0,0);b.a.bindBuffer(b.a.ARRAY_BUFFER,b.L);b.a.vertexAttribPointer(a.W,2,b.a.FLOAT,!1,0,0);b.a.bindBuffer(b.a.ELEMENT_ARRAY_BUFFER,b.K);b.a.drawElements(b.a.TRIANGLES,b.K.N,b.a.UNSIGNED_SHORT,0)}}g.ba=function(){return!1};window.Pano=k;k.prototype.isAvailable=k.prototype.fa;k.prototype.init=k.prototype.Y;k.prototype.setSize=k.prototype.V;k.prototype.setImage=k.prototype.la;k.prototype.fullscreen=k.prototype.ba;k.prototype.setFovScale=k.prototype.O;k.prototype.getFovScale=k.prototype.ca;
k.prototype.setVideo=k.prototype.ma;k.prototype.hasVideo=k.prototype.da;k.prototype.clearVideo=k.prototype.Z;k.prototype.playVideo=k.prototype.ka;k.prototype.pauseVideo=k.prototype.ja;k.prototype.isVideoPlaying=k.prototype.ga;function q(a){this.a=a;for(var b=[],c=[],d=[],e=0,f=0;33>e;e++)for(var h=Math.sin(e*Math.PI/32),n=Math.cos(e*Math.PI/32),l=0;33>l;l++,f++){var B=Math.cos(2*l*Math.PI/32);b[3*f+0]=Math.sin(2*l*Math.PI/32)*h;b[3*f+1]=n;b[3*f+2]=B*h;d[2*f+0]=1-l/32;d[2*f+1]=e/32}for(f=e=0;32>e;e++)for(l=0;32>l;l++,f++)c[6*f+0]=33*e+l,c[6*f+1]=33*e+(l+1),c[6*f+2]=33*(e+1)+l,c[6*f+3]=33*e+(l+1),c[6*f+4]=33*(e+1)+(l+1),c[6*f+5]=33*(e+1)+l;this.B=this.a.createBuffer();this.a.bindBuffer(a.ARRAY_BUFFER,this.B);this.a.bufferData(a.ARRAY_BUFFER,
new Float32Array(b),this.a.STATIC_DRAW);this.B.S=3;this.B.N=1089;this.L=this.a.createBuffer();this.a.bindBuffer(a.ARRAY_BUFFER,this.L);this.a.bufferData(a.ARRAY_BUFFER,new Float32Array(d),this.a.STATIC_DRAW);this.L.S=2;this.L.N=1089;this.K=a.createBuffer();this.a.bindBuffer(a.ELEMENT_ARRAY_BUFFER,this.K);this.a.bufferData(a.ELEMENT_ARRAY_BUFFER,new Uint16Array(c),this.a.STATIC_DRAW);this.K.N=6144};function r(a){this.a=a;this.oa="shaders/unlit_texture.vs";this.aa="shaders/unlit_texture.fs";this.F=[null,null]}function t(a,b){y([a.oa,a.aa],function(c){a.F[0]=c[0];a.F[1]=c[1];b()},function(a){alert('Failed to download "'+a+'"')})};function y(a,b,c){function d(a,c){h[c]=a;f++;f==e&&b(h)}for(var e=a.length,f=0,h=[],n=0;n<e;n++)z(a[n],n,d,c)}function z(a,b,c,d){var e=new XMLHttpRequest;e.open("GET",a,!0);e.onreadystatechange=function(){4==e.readyState&&(200==e.status?c(e.responseText,b):d(a))};e.send(null)};function m(a){this.a=a;this.ea=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?!0:!1;this.h=$("<video></video>");this.h.hide()}function v(a,b){if((new URL(b)).origin!==window.location.origin){var c=new Image;c.crossOrigin="";c.src=b;return c}return a}function w(a,b,c){A(a,b,a.a.createTexture(),c)}function x(a,b,c,d){var e=a.a.createTexture();a.h.attr("src",b);a.h.attr("loop",!0);a.I=!1;a.m=setInterval(function(){src=a.h.get(0);A(a,src,e,d)},1E3/c)}
m.prototype.play=function(){null!=this.m&&(this.h.get(0).play(),this.I=!0)};m.prototype.pause=function(){null!=this.m&&(this.h.get(0).pause(),this.I=!1)};
function A(a,b,c,d){function e(a){return 0==(a&a-1)}function f(a){--a;for(var c=1;32>c;c<<=1)a=a|a>>c;return a+1}a.a.bindTexture(a.a.TEXTURE_2D,c);if(a.ea&&(!e(b.width)||!e(b.height))){var h=document.createElement("canvas");for(h.width=f(b.width);2048<h.width;)h.width/=2;for(h.height=f(b.height);2048<h.height;)h.height/=2;h.getContext("2d").drawImage(b,0,0,h.width,h.height);b=h}a.a.texImage2D(a.a.TEXTURE_2D,0,a.a.RGBA,a.a.RGBA,a.a.UNSIGNED_BYTE,b);a.a.texParameteri(a.a.TEXTURE_2D,a.a.TEXTURE_MAG_FILTER,
a.a.LINEAR);a.a.texParameteri(a.a.TEXTURE_2D,a.a.TEXTURE_MIN_FILTER,a.a.LINEAR);a.a.texParameteri(a.a.TEXTURE_2D,a.a.TEXTURE_WRAP_S,a.a.CLAMP_TO_EDGE);a.a.texParameteri(a.a.TEXTURE_2D,a.a.TEXTURE_WRAP_T,a.a.CLAMP_TO_EDGE);a.a.bindTexture(a.a.TEXTURE_2D,null);null!=d&&d(c)};function p(a,b){var c=this;this.o=!1;this.P=mat4.create();mat4.identity(this.P);mat4.translate(this.P,[0,0,0]);this.w=mat4.create();mat4.identity(this.w);this.G;this.H;this.b=this.c=this.j=this.u=this.s=0;this.J=b;this.canvas=a;this.canvas.addEventListener("mousedown",function(a){c.o=!0;null!=c.g&&(clearInterval(c.g),c.g=null);var b=c.canvas.getBoundingClientRect(),f=800/c.canvas.width,h=(a.clientY-b.top)*f;c.G=(a.clientX-b.left)*f;c.H=h},!0);this.canvas.addEventListener("mousemove",function(a){if(c.o){var b=
c.canvas.getBoundingClientRect(),f=800/c.canvas.width;C(c,(a.clientX-b.left)*f,(a.clientY-b.top)*f);u(c.J)}},!0);this.canvas.addEventListener("mouseup",function(){c.o=!1;c.g=setInterval(function(){D(c);u(c.J)},1E3/60)},!0);this.canvas.addEventListener("touchstart",function(a){a.preventDefault();c.o=!0;null!=c.g&&(clearInterval(c.g),c.g=null);var b=c.canvas.getBoundingClientRect(),f=800/c.canvas.width,h=(a.targetTouches[0].pageY-b.top)*f;c.G=(a.targetTouches[0].pageX-b.left)*f;c.H=h},!0);this.canvas.addEventListener("touchmove",
function(a){a.preventDefault();if(c.o){var b=c.canvas.getBoundingClientRect(),f=800/c.canvas.width;C(c,(a.targetTouches[0].pageX-b.left)*f,(a.targetTouches[0].pageY-b.top)*f);u(c.J)}},!0);this.canvas.addEventListener("touchend",function(){c.o=!1;c.g=setInterval(function(){D(c);u(c.J)},1E3/60)},!0)}p.prototype.reset=function(){this.c=this.j=this.u=this.s=0;this.w=mat4.create();mat4.identity(this.w)};
function C(a,b,c){var d=a.G-b,e=a.H-c;a.G=b;a.H=c;a.s=d;a.u=e;b=.25*a.b/90;a.j+=d*b;a.c+=e*b;90<a.c?a.c=90:-90>a.c&&(a.c=-90);d=mat4.create();mat4.identity(d);mat4.rotate(d,a.c*Math.PI/180,[1,0,0]);mat4.rotate(d,a.j*Math.PI/180,[0,1,0]);a.w=d}
function D(a){a.s*=.95;a.u*=.95;.01>Math.abs(a.s)&&.01>Math.abs(a.u)&&(clearInterval(a.g),a.g=null);var b=a.u,c=.25*a.b/90;a.j+=a.s*c;a.c+=b*c;90<a.c?a.c=90:-90>a.c&&(a.c=-90);b=mat4.create();mat4.identity(b);mat4.rotate(b,a.c*Math.PI/180,[1,0,0]);mat4.rotate(b,a.j*Math.PI/180,[0,1,0]);a.w=b};
