function h(){this.c=this.s=84;this.N=mat4.create();this.O=mat4.create();this.C=null}
h.prototype.T=function(a){var b=this;this.L=!0;try{this.a=a.getContext("experimental-webgl"),this.P(a.width,a.height)}catch(c){this.L=!1;return}this.a.clearColor(1,0,1,1);this.a.enable(this.a.DEPTH_TEST);this.c=this.a.G/this.a.H*this.s*1;this.u=new l(a,this);this.u.J(this.c);this.$=new n(this.a);var d=new p(this.a);q(d,function(){var a;a=d.a.createShader(d.a.VERTEX_SHADER);d.a.shaderSource(a,d.v[0]);d.a.compileShader(a);if(d.a.getShaderParameter(a,d.a.COMPILE_STATUS)){var c=d.a.createShader(d.a.FRAGMENT_SHADER);
d.a.shaderSource(c,d.v[1]);d.a.compileShader(c);d.a.getShaderParameter(c,d.a.COMPILE_STATUS)?(shaderPgm=d.a.createProgram(),d.a.attachShader(shaderPgm,a),d.a.attachShader(shaderPgm,c),d.a.linkProgram(shaderPgm),d.a.getProgramParameter(shaderPgm,d.a.LINK_STATUS)||alert("Unable to initialize the shader program."),shaderPgm.S=d.a.getAttribLocation(shaderPgm,"aVertexPosition"),d.a.enableVertexAttribArray(shaderPgm.S),shaderPgm.R=d.a.getAttribLocation(shaderPgm,"aTextureCoord"),d.a.enableVertexAttribArray(shaderPgm.R),
shaderPgm.Z=d.a.getUniformLocation(shaderPgm,"uPMatrix"),shaderPgm.Y=d.a.getUniformLocation(shaderPgm,"uMVMatrix"),a=shaderPgm):(alert(d.a.getShaderInfoLog(c)),a=null)}else alert(d.a.getShaderInfoLog(a)),a=null;b.m=a;r(b)})};h.prototype.U=function(){return this.L};h.prototype.P=function(a,b){this.a.H=a;this.a.G=b};h.prototype.V=function(a){var b=this;this.C=null;t(new u(this.a),a,function(a){b.C=a;b.u.reset();r(b)})};
h.prototype.J=function(a){this.s=30+90*(1-a/100);this.c=this.a.G/this.a.H*this.s*1;this.u.J(this.c);r(this)};
function r(a){if(null!=a.m&&(a.a.viewport(0,0,a.a.H,a.a.G),a.a.clear(a.a.COLOR_BUFFER_BIT|a.a.DEPTH_BUFFER_BIT),null!=a.C)){mat4.perspective(a.c,a.a.H/a.a.G,.1,10,a.O);var b=a.u;mat4.multiply(b.K,b.l,a.N);a.a.useProgram(a.m);a.a.activeTexture(a.a.TEXTURE0);a.a.bindTexture(a.a.TEXTURE_2D,a.C);a.a.uniform1i(a.a.getUniformLocation(a.m,"uSampler"),0);a.a.uniformMatrix4fv(a.m.Z,!1,a.O);a.a.uniformMatrix4fv(a.m.Y,!1,a.N);b=a.$;a=a.m;b.a.bindBuffer(b.a.ARRAY_BUFFER,b.o);b.a.vertexAttribPointer(a.S,b.o.M,
b.a.FLOAT,!1,0,0);b.a.bindBuffer(b.a.ARRAY_BUFFER,b.F);b.a.vertexAttribPointer(a.R,2,b.a.FLOAT,!1,0,0);b.a.bindBuffer(b.a.ELEMENT_ARRAY_BUFFER,b.D);b.a.drawElements(b.a.TRIANGLES,b.D.I,b.a.UNSIGNED_SHORT,0)}}window.Pano=h;h.prototype.isAvailable=h.prototype.U;h.prototype.init=h.prototype.T;h.prototype.setSize=h.prototype.P;h.prototype.setImage=h.prototype.V;function n(a){this.a=a;for(var b=[],c=[],d=[],f=0,e=0;33>f;f++)for(var g=Math.sin(f*Math.PI/32),m=Math.cos(f*Math.PI/32),k=0;33>k;k++,e++){var x=Math.cos(2*k*Math.PI/32);b[3*e+0]=Math.sin(2*k*Math.PI/32)*g;b[3*e+1]=m;b[3*e+2]=x*g;d[2*e+0]=1-k/32;d[2*e+1]=f/32}for(e=f=0;32>f;f++)for(k=0;32>k;k++,e++)c[6*e+0]=33*f+k,c[6*e+1]=33*f+(k+1),c[6*e+2]=33*(f+1)+k,c[6*e+3]=33*f+(k+1),c[6*e+4]=33*(f+1)+(k+1),c[6*e+5]=33*(f+1)+k;this.o=this.a.createBuffer();this.a.bindBuffer(a.ARRAY_BUFFER,this.o);this.a.bufferData(a.ARRAY_BUFFER,
new Float32Array(b),this.a.STATIC_DRAW);this.o.M=3;this.o.I=1089;this.F=this.a.createBuffer();this.a.bindBuffer(a.ARRAY_BUFFER,this.F);this.a.bufferData(a.ARRAY_BUFFER,new Float32Array(d),this.a.STATIC_DRAW);this.F.M=2;this.F.I=1089;this.D=a.createBuffer();this.a.bindBuffer(a.ELEMENT_ARRAY_BUFFER,this.D);this.a.bufferData(a.ELEMENT_ARRAY_BUFFER,new Uint16Array(c),this.a.STATIC_DRAW);this.D.I=6144};function p(a){this.a=a;this.aa="shaders/unlit_texture.vs";this.W="shaders/unlit_texture.fs";this.v=[null,null]}function q(a,b){v([a.aa,a.W],function(c){a.v[0]=c[0];a.v[1]=c[1];b()},function(a){alert('Failed to download "'+a+'"')})};function v(a,b,c){function d(a,c){g[c]=a;e++;e==f&&b(g)}for(var f=a.length,e=0,g=[],m=0;m<f;m++)w(a[m],m,d,c)}function w(a,b,c,d){var f=new XMLHttpRequest;f.open("GET",a,!0);f.onreadystatechange=function(){4==f.readyState&&(200==f.status?c(f.responseText,b):d(a))};f.send(null)};function u(a){this.a=a;this.X=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?!0:!1}function t(a,b,c){y(a,b,a.a.createTexture(),c)}
function y(a,b,c,d){function f(a){return 0==(a&a-1)}function e(a){--a;for(var c=1;32>c;c<<=1)a=a|a>>c;return a+1}a.a.bindTexture(a.a.TEXTURE_2D,c);if(self.X&&(!f(b.width)||!f(b.height))){var g=document.createElement("canvas");for(g.width=e(b.width);2048<g.width;)g.width/=2;for(g.height=e(b.height);2048<g.height;)g.height/=2;g.getContext("2d").drawImage(b,0,0,g.width,g.height);b=g}a.a.texImage2D(a.a.TEXTURE_2D,0,a.a.RGBA,a.a.RGBA,a.a.UNSIGNED_BYTE,b);a.a.texParameteri(a.a.TEXTURE_2D,a.a.TEXTURE_MAG_FILTER,
a.a.LINEAR);a.a.texParameteri(a.a.TEXTURE_2D,a.a.TEXTURE_MIN_FILTER,a.a.LINEAR);a.a.texParameteri(a.a.TEXTURE_2D,a.a.TEXTURE_WRAP_S,a.a.CLAMP_TO_EDGE);a.a.texParameteri(a.a.TEXTURE_2D,a.a.TEXTURE_WRAP_T,a.a.CLAMP_TO_EDGE);a.a.bindTexture(a.a.TEXTURE_2D,null);null!=d&&d(c)};function l(a,b){var c=this;this.h=!1;this.K=mat4.create();mat4.identity(this.K);mat4.translate(this.K,[0,0,0]);this.l=mat4.create();mat4.identity(this.l);this.w;this.A;this.c=this.b=this.g=this.j=this.i=0;this.B=b;this.canvas=a;this.canvas.addEventListener("mousedown",function(a){c.h=!0;null!=c.f&&(clearInterval(c.f),c.f=null);var b=c.canvas.getBoundingClientRect(),e=800/c.canvas.width,g=(a.clientY-b.top)*e;c.w=(a.clientX-b.left)*e;c.A=g},!0);this.canvas.addEventListener("mousemove",function(a){if(c.h){var b=
c.canvas.getBoundingClientRect(),e=800/c.canvas.width;z(c,(a.clientX-b.left)*e,(a.clientY-b.top)*e);r(c.B)}},!0);this.canvas.addEventListener("mouseup",function(){c.h=!1;c.f=setInterval(function(){A(c);r(c.B)},1E3/60)},!0);this.canvas.addEventListener("touchstart",function(a){a.preventDefault();c.h=!0;null!=c.f&&(clearInterval(c.f),c.f=null);var b=c.canvas.getBoundingClientRect(),e=800/c.canvas.width,g=(a.targetTouches[0].pageY-b.top)*e;c.w=(a.targetTouches[0].pageX-b.left)*e;c.A=g},!0);this.canvas.addEventListener("touchmove",
function(a){a.preventDefault();if(c.h){var b=c.canvas.getBoundingClientRect(),e=800/c.canvas.width;z(c,(a.targetTouches[0].pageX-b.left)*e,(a.targetTouches[0].pageY-b.top)*e);r(c.B)}},!0);this.canvas.addEventListener("touchend",function(){c.h=!1;c.f=setInterval(function(){A(c);r(c.B)},1E3/60)},!0)}l.prototype.reset=function(){this.b=this.g=this.j=this.i=0;this.l=mat4.create();mat4.identity(this.l)};l.prototype.J=function(a){this.c=a};
function z(a,b,c){var d=a.w-b,f=a.A-c;a.w=b;a.A=c;a.i=d;a.j=f;b=.25*a.c/90;a.g+=d*b;a.b+=f*b;90<a.b?a.b=90:-90>a.b&&(a.b=-90);d=mat4.create();mat4.identity(d);mat4.rotate(d,a.b*Math.PI/180,[1,0,0]);mat4.rotate(d,a.g*Math.PI/180,[0,1,0]);a.l=d}
function A(a){a.i*=.95;a.j*=.95;.01>Math.abs(a.i)&&.01>Math.abs(a.j)&&(clearInterval(a.f),a.f=null);var b=a.j,c=.25*a.c/90;a.g+=a.i*c;a.b+=b*c;90<a.b?a.b=90:-90>a.b&&(a.b=-90);b=mat4.create();mat4.identity(b);mat4.rotate(b,a.b*Math.PI/180,[1,0,0]);mat4.rotate(b,a.g*Math.PI/180,[0,1,0]);a.l=b};
